import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SearchBar from "@/components/SearchBar";
import Categories from "@/components/Categories";
import Footer from "@/components/Footer";
import { MyProvider } from "./MyProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-full h-screen px-8 py-2 flex flex-col`}
      >
        <MyProvider>
          <section className="header">
            <SearchBar />
            <Categories />
          </section>
          {children}
          <section className="footer relative bottom-0">
            <Footer />
          </section>
        </MyProvider>
      </body>
    </html>
  );
}
